name: Random Failure Test

on:  
  pull_request:

jobs:
  check-files:
    runs-on: ubuntu-latest
    outputs:
      backend_changed: ${{ steps.filter.outputs.backend_changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch Base Branch
        run: git fetch origin $GITHUB_BASE_REF --depth=1

      - name: Check for Backend File Changes
        id: filter
        run: |
          if git diff --name-only origin/$GITHUB_BASE_REF | grep '^backend/'; then
            echo "backend_changed=true" >> $GITHUB_ENV
            echo "backend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "backend_changed=false" >> $GITHUB_ENV
            echo "backend_changed=false" >> $GITHUB_OUTPUT
          fi

  skip-tests:
    needs: check-files
    runs-on: ubuntu-latest
    if: needs.check-files.outputs.backend_changed == 'false'
    steps:
      - name: Skip Tests
        run: echo "No GTM changes, skipping E2E tests."

  random-fail:
    needs: check-files
    runs-on: ubuntu-latest
    if: needs.check-files.outputs.backend_changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Random Failure Step
        run: |
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "✅ Success!"
            exit 0
          else
            echo "❌ Random Failure!"
            exit 1
          fi
